// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEBASE_H
#define DRIVEBASE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../DeadSwipe.h"
#include "../dbDefs.h"
#include "../ghettoPID.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class DriveBase: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* frontLeft;
	SpeedController* backLeft;
	SpeedController* frontRight;
	SpeedController* backRight;
	RobotDrive* dbTank;
	Gyro* dbGyro;
	Encoder* dbLeftEncoder;
	Encoder* dbRightEncoder;
	Encoder* dbMidEncoder;
	SpeedController* middleLeft;
	SpeedController* middleRight;
	RobotDrive* dbMiddle;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	DriveBase();
	void InitDefaultCommand();
	ghettoPID* dbSigmoid;
	void JDrive(Joystick* LeftStick, Joystick* RightStick);
	void Drive(float left, float right, float strafe);
	void TDrive(float left, float right);
	void Strafe(float speed);
	void ResetGyro();
	void ResetEncoder(int x);
	float GetAngle();
	void GetEncoder();
	double GetDistance(int x);
	void DoNothing();
};

#endif
