// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoTurn.h"

AutoTurn::AutoTurn(float target, float direction, float speed) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveBase);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	this->Target = target;
	this->Direction = direction;
	this->Speed = speed;
}

// Called just before this Command runs the first time
void AutoTurn::Initialize() {
	Robot::driveBase->ResetEncoder(9); // use the default
}

// Called repeatedly when this Command is scheduled to run
void AutoTurn::Execute() {
	if (Direction > 0) {
		Robot::driveBase->TDrive(this->Speed, -this->Speed);
	} else {
		Robot::driveBase->TDrive(-this->Speed, this->Speed);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool AutoTurn::IsFinished() {
	if (this->Direction > 0) {
		return Robot::driveBase->GetAngle() >= this->Target;
	} else {
		return Robot::driveBase->GetAngle() <= this->Target;
	}
}

// Called once after isFinished returns true
void AutoTurn::End() {
	Robot::driveBase->Drive(0.0, 0.0, 0.0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoTurn::Interrupted() {
	End();
}
