// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoDrive.h"
#include "Commands/AutoIntake.h"
#include "Commands/AutoTurn.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DoNuffin.h"
#include "Commands/ElevatorManual.h"
#include "Commands/ElevatorMove.h"
#include "Commands/ElevatorOpen.h"
#include "Commands/TeleIntake.h"
#include "Commands/TeleopDrive.h"
#include "Commands/ThreeCans.h"
#include "Commands/ToteCan.h"
#include "Commands/XAxisDrive.h"
#include "Commands/YAXisDrive.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	gamepad = new Joystick(2);
	
	right = new Joystick(1);
	
	left = new Joystick(0);
	
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("TeleopDrive", new TeleopDrive());

	SmartDashboard::PutData("ElevatorOpen", new ElevatorOpen());

	SmartDashboard::PutData("ElevatorMove", new ElevatorMove());

	SmartDashboard::PutData("YAXisDrive", new YAXisDrive());

	SmartDashboard::PutData("XAxisDrive", new XAxisDrive());

	SmartDashboard::PutData("TeleIntake", new TeleIntake());

	SmartDashboard::PutData("AutoIntake", new AutoIntake());

	SmartDashboard::PutData("ElevatorManual", new ElevatorManual());

	SmartDashboard::PutData("DoNuffin", new DoNuffin());

	SmartDashboard::PutData("ToteCan", new ToteCan());

	SmartDashboard::PutData("ThreeCans", new ThreeCans());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	SmartDashboard::PutData("AutoTurn", new AutoTurn(90.0,1,0.5));

	SmartDashboard::PutData("AutoDrive", new AutoDrive(12.0,12.0,0.0, 0.5, 0.5, 0.0));
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getGamepad() {
	return gamepad;
}

Joystick* OI::getRight() {
	return right;
}

Joystick* OI::getLeft() {
	return left;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
